### ISSUE TITLE
How to use mujava to mutate the entire project?

### ISSUE THREAD

**Issue by Provence613** [saiema/MuJava#12]
I want to mutate the entire project. When I put the entire project into the src folder and run it, it will report an error. Like [ERROR] for class org.joda.time.DateTime => org.joda.time.base.BaseDateTime. So what can I do to mutate the entire project?

**Comment by saiema** [comment]
Hi, muJava++ only supports mutating one class at a time.

Even though I don't understand what error you are getting, it seems that you are trying to mutate a project from defects4j?

([muJava](https://github.com/EpsilonX/MuJava) uses a custom Java parser which muJava++ improves upon just a bit, that means that it supports mainly Java 1.7, I just wanted to clarify that if you wanted to use it for a Java 1.8+ project.

Regards.

**Comment by Provence613** [comment]
> Hi, muJava++ only supports mutating one class at a time.
> 
> Even though I don't understand what error you are getting, it seems that you are trying to mutate a project from defects4j?
> 
> ([muJava](https://github.com/EpsilonX/MuJava) uses a custom Java parser which muJava++ improves upon just a bit, that means that it supports mainly Java 1.7, I just wanted to clarify that if you wanted to use it for a Java 1.8+ project.
> 
> Regards.

Hi,Thank you for your answer.
My problem now is that I want to mutate the java files in the entire joda-time project, but the java files will call the methods of other classes of the package or the methods of other package classes. Can situations like this be handled by mujava?
No matter I put the whole project or a single java file into the src folder, it will report an error.
If I put a single java file into the src folder, the log file shows the following error: 
```
[Error] MonthDay.java java.lang.NoClassDefFoundError: Could not initialize class org.joda.time.DateTimeFieldType
MutantsGenPanel:
java.lang.NoClassDefFoundError: Could not initialize class org.joda.time.DateTimeFieldType
```
If I put the whole project into the src folder, the log file shows the following error: 
```
[Error] org\joda\time\Chronology.java java.lang.NoClassDefFoundError: Could not initialize class org.joda.time.DateTimeZone
MutantsGenPanel:
java.lang.NoClassDefFoundError: Could not initialize class org.joda.time.DateTimeZone
```
Regards.

**Comment by saiema** [comment]
It seems like you are not using muJava++ but muJava, because of the `MutantsGenPanel` part of the error you are getting. And the error you are getting appears to be related to the classpath not being correctly defined: you have classes of your project that are not being found.

For an example to run muJava++ please check the [latest release](https://github.com/saiema/MuJava/releases/tag/1.8.5).

As for the initial question, I understand you have a class A which you want to mutate and inside that class there is a call to a method m from class B, muJava++ will handle mutating that call.

muJava++ has several operators not found in muJava (some from PIT, some from MAJOR, and some which are original for muJava++), also it supports several analysis which are not supported in muJava such as toughness analysis (how much tests a mutant is able to survive, as a relation with total tests) and dynamic mutant subsumption which allows to analyze esencial and redundant mutants, nevertheless this analysis and extra operators are only useful on specific studies, what I mean is that if you are just trying mutation testing then muJava++ may be a little too much.

**Comment by Provence613** [comment]
Thank you very much for your answers, I will learn how to use mujava ++.
Regards.

**Comment by saiema** [comment]
I'll close the issue, if you have any more questions you can open a new issue or if it's more of a question about how to use mujava++ then you can send me an email (there's an email in my profile information).
